### ISSUE TITLE
At option to compare 'regions/cities', at least the major ones that are of interest

### ISSUE THREAD

**Issue by hershkoy** [Lrakotoson/Covid-19#20]
It would be very helpful to see regions such as Wuhan, New York, Lombardy Italy, Madrid, London Independently.

**Comment by Lrakotoson** [comment]
Hi,
Yes, the city details were there, at least until yesterday.
There is an important update of the data form, so we will keep the current configuration temporarily.

There are also some changes in the data to be analyzed, including the relevance of the recovery analysis.

**Comment by Lrakotoson** [comment]
#23
