### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by PierreLepagnol** [Lrakotoson/Covid-19#8]
Hi Loic,
What a great work you've made with your team.
I've tried to launch your app in local to add a feature, but you haven't added `/script` in your repo.
Therefore no one can contribute...

Is there a posibility to add the missing files ?

**Comment by Lrakotoson** [comment]
Hi, @PierreLepagnol
I appreciate you wanting to contribute.
It was there, but the team voted to keep the kernel script private until March 16th, just to be safe.
However, we can discuss it privately about getting a preview.

**Comment by Lrakotoson** [comment]
Hi, @PierreLepagnol 
I hope you're still enthusiastic about contributing since I'm happy to announce that the repo is now open for contributions and therefore the files in `scripts/` are available.
We have also updated the README file by adding the **Contribution guidelines**.
